2020-01-02 09:56:31,466 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\Cert25\app\__init__.py:48]
2020-01-02 09:59:58,367 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\Cert25\app\__init__.py:48]
2020-01-02 10:00:25,936 ERROR: Exception on /login [POST] [in c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Users\richa\OneDrive\Projects\Cert25\app\routes.py", line 194, in login
    return render_template('home.html',nameOfUser=nameOfUser)
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "c:\Users\richa\OneDrive\Projects\Cert25\app\templates\home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\Users\richa\OneDrive\Projects\Cert25\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\Users\richa\OneDrive\Projects\Cert25\app\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\Users\richa\OneDrive\Projects\Cert25\app\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\Users\richa\OneDrive\Projects\Cert25\app\templates\bootstrap\base.html", line 33, in block "html"
    {% block body -%}
  File "c:\Users\richa\OneDrive\Projects\Cert25\app\templates\bootstrap\base.html", line 36, in block "body"
    {% block content -%}
  File "c:\Users\richa\OneDrive\Projects\Cert25\app\templates\base.html", line 118, in block "content"
    {% block app_content %}{% endblock %}
  File "c:\Users\richa\OneDrive\Projects\Cert25\app\templates\home.html", line 136, in block "app_content"
    {{ form.hidden_tag() }}
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2020-01-02 10:15:20,761 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\Cert25\app\__init__.py:48]
2020-01-02 10:45:38,432 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\Cert25\app\__init__.py:48]
2020-01-02 10:46:59,410 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\Cert25\app\__init__.py:48]
2020-01-02 10:48:03,823 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\Cert25\app\__init__.py:48]
2020-01-02 10:49:28,488 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\Cert25\app\__init__.py:48]
2020-01-02 10:54:24,716 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\Cert25\app\__init__.py:48]
2020-01-07 10:31:56,191 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\Cert25\app\__init__.py:48]
2020-01-07 10:33:17,827 ERROR: Exception on /login [POST] [in c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Users\richa\OneDrive\Projects\Cert25\app\routes.py", line 155, in login
    pw1=user.set_password("infosys03")
AttributeError: 'NoneType' object has no attribute 'set_password'
2020-01-08 09:36:44,812 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\Cert25\app\__init__.py:48]
