2020-01-01 16:32:05,961 ERROR: Exception on / [GET] [in c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Users\richa\OneDrive\Projects\Cert25\app\routes.py", line 70, in home
    certifiedShop2=certifiedShop2,notCertifiedShop1=notCertifiedShop1,notCertifiedShop2=notCertifiedShop2,noCertification=noCertification)
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "c:\Users\richa\OneDrive\Projects\Cert25\app\templates\home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\Users\richa\OneDrive\Projects\Cert25\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\Users\richa\OneDrive\Projects\Cert25\app\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\Users\richa\OneDrive\Projects\Cert25\app\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\Users\richa\OneDrive\Projects\Cert25\app\templates\bootstrap\base.html", line 33, in block "html"
    {% block body -%}
  File "c:\Users\richa\OneDrive\Projects\Cert25\app\templates\bootstrap\base.html", line 34, in block "body"
    {% block navbar %}
  File "c:\Users\richa\OneDrive\Projects\Cert25\app\templates\base.html", line 33, in block "navbar"
    <a class="nav-link" href="{{ url_for('notcertified') }}">NOT CERTIFIED</a>
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\app.py", line 2080, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\werkzeug\routing.py", line 2007, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'notcertified'. Did you mean 'certify' instead?
2020-01-01 16:38:53,833 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\Cert25\app\__init__.py:48]
2020-01-01 16:41:05,107 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\Cert25\app\__init__.py:48]
2020-01-01 16:44:04,384 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\Cert25\app\__init__.py:48]
2020-01-01 16:44:28,005 ERROR: Exception on /trainingClass/1047/ [GET] [in c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\richa\OneDrive\Projects\Cert25\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Users\richa\OneDrive\Projects\Cert25\app\routes.py", line 658, in trainingClass
    print (currentTrainingClass.classDate)
AttributeError: 'ResultProxy' object has no attribute 'classDate'
2020-01-01 16:45:55,017 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\Cert25\app\__init__.py:48]
2020-01-01 16:51:16,167 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\Cert25\app\__init__.py:48]
2020-01-01 16:53:21,189 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\Cert25\app\__init__.py:48]
2020-01-01 16:55:35,139 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\Cert25\app\__init__.py:48]
2020-01-01 16:57:56,313 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\Cert25\app\__init__.py:48]
2020-01-01 16:59:27,321 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\Cert25\app\__init__.py:48]
2020-01-01 17:03:40,282 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\Cert25\app\__init__.py:48]
2020-01-01 17:09:56,244 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\Cert25\app\__init__.py:48]
2020-01-01 17:11:11,867 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\Cert25\app\__init__.py:48]
2020-01-01 17:13:40,174 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\Cert25\app\__init__.py:48]
2020-01-01 17:17:33,821 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\Cert25\app\__init__.py:48]
2020-01-01 17:18:55,922 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\Cert25\app\__init__.py:48]
2020-01-01 17:27:17,018 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\Cert25\app\__init__.py:48]
2020-01-01 17:33:19,005 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\Cert25\app\__init__.py:48]
